from setuptools import setup, find_packages

setup(
    name="unsloth-medisage",
    version="1.0.0",
    author="Manoj Kumar Sunkara",
    description="Fine-Tuning Llama-3-8B-Instruct for Medical Question Answering using Unsloth",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "unsloth",
        "torch",
        "torchvision",
        "torchaudio",
        "transformers>=4.45.0",
        "datasets",
        "trl",
        "accelerate",
        "bitsandbytes",
        "peft",
        "sentencepiece",
        "protobuf",
        "numpy",
        "pandas",
        "scikit-learn",
        "tqdm",
        "huggingface_hub",
        "safetensors",
    ],
    keywords=[
        "Medical QA",
        "LLM",
        "Llama-3",
        "Unsloth",
        "Medical AI",
        "Fine-Tuning",
        "Healthcare",
        "Transformers",
    ],
    license="MIT",
)